### ISSUE TITLE
Auth error with active consumer key but not using "YOUR_KEY_HERE"

### ISSUE THREAD

**Issue by sunzu** [gquemener/7digital-client#4]
I am working in a project that consumes 7Digital API and I am using your 7digital-client. When using "YOUR_KEY_HERE" as consumer key it works fine, but if I replace it with a real consumer key like "my-key" I get a 401 error:

```
SevenDigital\Exception\Exception: 7digital API responded with an error 401. in SevenDigital\Service->request() (line 79 of/Users/jorge/Workspace/tonspion.de/www/sites/all/vendor/gquemener/7digital-client/src/SevenDigital/Service.php).
```

The consumer key is "active" as this call in browser or curl works fine:

http://api.7digital.com/1.2/artist/search?q=queen&oauth_consumer_key=my-key&country=DE

Just like:

http://api.7digital.com/1.2/artist/search?q=queen&oauth_consumer_key=YOUR_KEY_HERE&country=DE

This is how I use your client:

``` php
  use SevenDigital\ApiClient;
  $client = new ApiClient("my-key");
  $artist = $client->getArtistService(); //This call returns the error when using "my-key" as consumer key
```

Do you have any clue about where is the problem? Maybe a default value with request auth options.

Thanks for your help and your good work with this library.

**Comment by gquemener** [comment]
Hello Jorge,

It seems that the 7digital api does not really provide accurate error response.
Problem is that the "country" parameter has not been sent in your query.
7digital should return an other response status code than 401 (like 400 or 422), as it can be confusing for debuging.

So, solution is to provide the country parameter whenever you call the search endpoint:

``` php
<?php
require __DIR__.'/vendor/autoload.php';

use SevenDigital\ApiClient;
$client = new ApiClient("tonspion");
$artist = $client->getArtistService();

die(var_dump($artist->search(array('country' => 'DE', 'q' => 'queen'))));
```

**Comment by sunzu** [comment]
Wow man! I have spent several hours looking for the bug and you did it in less than 5 minutes.
Thanks again!

**Comment by gquemener** [comment]
Quoting the 7digital api documentation:

> In order to be able to provide users with the maximum possible amount of content available in their country and display prices in their local currency whenever possible, all API methods accept a special parameter country. 
> **If a country code is not supplied, all operations will be actioned on the default store - currently the UK one.**

Well, this is incorrect.

**Comment by gquemener** [comment]
And btw, thanks for using this client :wink:

**Comment by filip-d** [comment]
This is expected behaviour. That specific key is set up with access to German catalogue only, meaning if no country code is provided in the request the API falls back to UK catalogue which the key doesn't have access to and returns 401 access denied. 
But we could definitely improve the error message to make it clearer.

@sunzu when posting any API queries/issues on public forums we strongly advise you to blank out any API keys and API secrets. I'd suggest you get in touch with us to change your API key as if someone picks it up from here and abuses it you'd end up getting blocked.

Thanks
Filip
7digital

**Comment by sunzu** [comment]
Thanks guys for your comments.
